name: Fabrication

on:
  push:
    branches:
      - main
    tags:
      - v*
    paths:
      - '**.sch'
      - '**.kicad_pcb'
      - '.github/workflows/*'
      - 'jlcpcb/*'
  pull_request:
    paths:
      - '**.sch'
      - '**.kicad_pcb'
      - '.github/workflows/*'
      - 'jlcpcb/*'

env:
  KIKIT: docker run --rm -v $PWD:/pcb -w /pcb --user $UID:$GROUPS yaqwsx/kikit kikit

jobs:
  docs:
    name: Documentation generation
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: SmartishMiniLED
            schematic: SmartishMiniLED.kicad_sch
            board: SmartishMiniLED.kicad_pcb

    steps:
    - uses: actions/checkout@v2

    - uses: nerdyscout/kicad-exports@v2.2
      with:
        config: docs.kibot.yaml
        dir: docs
        schema: ${{ matrix.schematic }}
        board: ${{ matrix.board }}

    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.name }}-docs
        path: docs

  fabrications:
    name: Fabrication
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: SmartishMiniLED
            schematic: SmartishMiniLED.kicad_sch
            board: SmartishMiniLED.kicad_pcb
    steps:
    - uses: actions/checkout@v2

    - name: Export JLCPCB fabrication files
      run: |
        ${{ env.KIKIT }} fab jlcpcb --assembly --schematic ${{ matrix.schematic }} --ignore J2,JP1 ${{ matrix.board }} ${{ matrix.name }}

    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.name }}
        path: |
          ${{ matrix.name }}/*.zip
          ${{ matrix.name }}/*.csv

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: 
      - docs
      - fabrications

    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - name: Download the built assets
      uses: actions/download-artifact@v2
      with:
        path: artifacts

    - name: Package up the combined assets
      run: |
        find artifacts
        version=${GITHUB_REF_NAME}
        for asset in SmartishMiniLED
        do
          for file in gerbers.zip bom.csv pos.csv
          do
            name=$(cut -d'.' -f1 <<< $file)
            ext=$(cut -d'.' -f2 <<< $file)
            mv artifacts/$asset/$file artifacts/$asset-$name-$version.$ext
          done
          rm -rf artifacts/$asset
        done
        mv artifacts/SmartishMiniLED-docs/docs/SmartishMiniLED-schematic.pdf artifacts/SmartishMiniLED-schematic-$version.pdf
        for asset in SmartishMiniLED-docs
        do
          rm -rf artifacts/$asset
        done
        find artifacts

    - name: Upload assets to latest release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: ${{ contains(github.ref, '-rc') }}
        files: |
          artifacts/*.zip
          artifacts/*.csv
          artifacts/*.pdf

